= Description du service factory
:toc: left

Le service factory est un module qui permet la création d'un service en fonction d'une demande client.

== Gestion d'un service via le service factory

[plantuml, format="svg", role="right"]
....
legend
Legend
endlegend

node Client

node Server {
    component "Reverse Proxy" as ReverseProxy
    component "Service Factory" as ServiceFactory
    component Service1
    component ServiceX

    ReverseProxy -left- ServiceFactory
    ServiceFactory -down- Service1
    ServiceFactory -down- ServiceX
    ReverseProxy -down- Service1
    ReverseProxy -down- ServiceX
}

Client -right- ReverseProxy
....

C'est par l'intermédiaire d'un reverse proxy que le client pourra communiquer avec :

* Un service factory
* Un service

== Description du service factory

Le service factory à pour rôle de gérer les services qui auront été créés suite à une demande d'execution d'un client.

Un client peut faire une demande, au service factory, de :

[%header,cols=3*]
|===
|Référence |Action  |Description

|1
|Création compte
|Créer un compte utilisateur

|2
|Création service
|Créer un service

|3
|Destruction service
|Détruire un service


|4
|Ajout
|Ajouter un compte de trading

|5
|Liste
|Lister les comptes de trading

|6
|Suppression
|Supprimer les comptes de trading

|7
|Modification
|Modifier les comptes de trading


|8
|Suppression compte perso
|Supprimer un compte personnel

|9
|Mot de passe oublié
|Réinitialisation du mot de passe

|10
|Liste Brokers
|Lister les Brokers

|11
|Connection
|Se connecter

|===

== Routes service factory

Les communication avec le service factory doivent se faire sur l'url suivante : `service_factory.domain.tld`.

[%header,cols=5*]
|===
|Référence |Verbe HTTP |Route |Données  |Réponse

|1
|POST
|/users/
a|
[source,json]
{
    "email": String,
    "password": String
}
a|
[source]
Status Code : 201

[source,json]
{
    "id": Integer
}

|2
|POST
|/service
a|
[source,json]
{
    "username": String,
    "password": String,
    "broker": String,
    "accountType": String
}
a|
[source]
Status Code : 200

[source,json]
{
    "urlws": String
}

|3
|DELETE
|/service/{id}
a|
[source,json]
{
    "urlws": String
}
a|
[source]
Status Code : 202

[source,json]
{
    "status": Boolean
}

|4
|POST
|/trading-accounts
a|
[source,json]
{
    "token": String
    "type compte": String
    "brokername": String
    "username": String
    "password": String
}
a|
[source]
Status Code : 201

[source,json]
{
    "id": Integer
}

|5
|GET
|/trading-accounts
a|
[source,json]
{
    "token": String
}
a|
[source]
Status Code : 202

[source,json]
{
    "array": Type de compte, brokername, username, password
}

|6
|DELETE
|/trading-accounts/{id}
a|
[source,json]
{
    "token": String
}
a|
[source]
Status Code : 204

[source,json]
{
    "id": Integer
}

|7
|PUT
|/trading-accounts/{id}
a|
[source,json]
{
    "token": String
    "type compte": String
    "brokername": String
    "username": String
    "password": String
}
a|
[source]
Status Code : 201

[source,json]
{
    "id": Integer
}

|8
|DELETE
|/service/{id}
a|
[source,json]
{
    "token": String
}
a|
[source]
Status Code : 204

|9
|POST
|/users/forgotten
a|
[source,json]
{
    "email": String
    "token": String
}
a|
[source]
Status Code : 201

|10
|GET
|/brokers
a|
[source,json]
{
    "token": String
}
a|
[source]
Status Code : 200

[source,json]
{
    "array": brokername, id
}

|11
|POST
|/users/auth
a|
[source,json]
{
    "email": String
    "password": String
}
a|
[source]
Status Code : 201

[source,json]
{
    "token":
}
|===

Les informations (informations de connection à un compte de trading) transmises par l'intermediaire des routes sont transmises au service pour sa création.

== Cahier de recettes

.Création d'un compte utilisateur via l'API
[%header,cols=5*]
|===
|Ref
|Context
|Url
|Data
|Result

|1
|Pas d'utilisateur existant en base de donées
|/users
a|
[source,json]
{
    "email": "john.doe@domain.tld",
    "password": "secret"
}
a|
[source,json]
{
    "id": 1
}

|1
|Pas d'utilisateur existant en base de donées avec un mot de passe trop cours
|/users
a|
[source,json]
{
    "email": "john.doe@domain.tld",
    "password": "pass"
}
a|
[source,json]
{
    "message": "password_to_short"
}

|1
|Pas d'utilisateur existant en base de donées avec un email invalid
|/users
a|
[source,json]
{
    "email": "john.doedomain.tld",
    "password": "secret"
}
a|
[source,json]
{
    "message": "invalid_email"
}

|1
|Pas d'utilisateur existant en base de donées, mais oublie la saisie du mot de passe
|/users
a|
[source,json]
{
    "email": "john.doe@domain.tld"
}
a|
[source,json]
{
    "message": "required_fields"
}

|1
|Pas d'utilisateur existant en base de donées, mais oublie la saisie de l'email
|/users
a|
[source,json]
{
    "password": "secret"
}
a|
[source,json]
{
    "message": "required_fields"
}

|1
|Un utilisateur "john.doe@domain.tld" existe en base de données
|/users
a|
[source,json]
{
    "email": "john.doe@domain.tld",
    "password": "secret"
}
a|
[source,json]
{
    "id": 1
}
<<<<<<< HEAD
|===

.Suppression d'un compte de trading via l'API
[%header,cols=5*]
|===
|Ref
|Context
|Url
|Data
|Result

|6
|Suppression de compte qui n'existe pas
|/trading-account/{id}
a|
[source,json]
{
    "delete account": "name account"
=======

|4
|Enregistrement du compte en Base
|/trading-accounts
a|
[source,json]
{
    "token": "token",
    "accountType": "DEMO"
    "brokerName": "nombroker"
    "userName": "username"
    "password": "secret"

>>>>>>> cde1214dcb94a17314d10c1505bb797670697fb1
}
a|
[source,json]
{
<<<<<<< HEAD
    "message": "account_successfully_deleted"
}

|6
|Suppression de compte qui n'appartient pas à l'utilisateur
|/trading-account/{id}
a|
[source,json]
{
    "delete account": "name account"
=======
    "id": 1
}

|4
|Enregistrement du compte en Base mais accountType non conforme
|/trading-accounts
a|
[source,json]
{
    "token": "token",
    "accountType": "1234"
    "brokerName": "nombroker"
    "userName": "username"
    "password": "secret"

>>>>>>> cde1214dcb94a17314d10c1505bb797670697fb1
}
a|
[source,json]
{
<<<<<<< HEAD
    "message": "account_successfully_deleted"
}

|6
|Suppression de compte avec succès
|/trading-account/{id}
a|
[source,json]
{
    "delete account": "name account"
=======
    "message": "bad_credentials"
}

|4
|Enregistrement du compte en Base mais brokerName non conforme
|/trading-accounts
a|
[source,json]
{
    "token": "token",
    "accountType": "DEMO"
    "brokerName": "test123"
    "userName": "username"
    "password": "secret"

>>>>>>> cde1214dcb94a17314d10c1505bb797670697fb1
}
a|
[source,json]
{
<<<<<<< HEAD
    "message": "account_successfully_deleted"
}
|===

.Modification d'un compte de trading via l'API
[%header,cols=5*]
|===
|Ref
|Context
|Url
|Data
|Result

|7
|Modification de compte avec succès
|/trading-account/{id}
a|
[source,json]
{
    "change account": "name account"
=======
    "message": "bad_credentials"
}

|4
|Enregistrement du compte en Base mais userName non conforme
|/trading-accounts
a|
[source,json]
{
    "token": "token",
    "accountType": "DEMO"
    "brokerName": "brokername"
    "userName": "badusername"
    "password": "secret"

}
a|
[source,json]
{
    "message": "bad_credentials"
}

|4
|Enregistrement du compte en Base mais password non conforme
|/trading-accounts
a|
[source,json]
{
    "token": "token",
    "accountType": "DEMO"
    "brokerName": "brokername"
    "userName": "username"
    "password": "invalidsecret"

>>>>>>> cde1214dcb94a17314d10c1505bb797670697fb1
}
a|
[source,json]
{
<<<<<<< HEAD
    "message": "account_modified_successfully"
}

|7
|Modification de compte n'appartenant pas à l'utilisateur
|/trading-account/{id}
a|
[source,json]
{
    "change account": "name account"
=======
    "message": "bad_credentials"
}

|5
|Lister les comptes de trading si comptes existants
|/trading-accounts
a|
[source,json]
{
    "token": "token"

>>>>>>> cde1214dcb94a17314d10c1505bb797670697fb1
}
a|
[source,json]
{
<<<<<<< HEAD
    "message": "account_modified_successfully"
}

|7
|Modification de compte avec data manquante
|/trading-account/{id}
a|
[source,json]
{
    "change account": "name account"
=======
    "array": "AccountType, brokerName, userName, password"
}

|5
|Lister les comptes de trading si comptes inexistants
|/trading-accounts
a|
[source,json]
{
    "token": "token"

>>>>>>> cde1214dcb94a17314d10c1505bb797670697fb1
}
a|
[source,json]
{
<<<<<<< HEAD
    "message": "missing_data"
}
|====
=======
    "array": ""
}
|===
>>>>>>> cde1214dcb94a17314d10c1505bb797670697fb1
