= Description du ServiceFactory
:toc: left

Le ServiceFactory est un module qui permet la création d'un service en fonction d'une demande client.

.TODO List

* Mettre en place un scan avec suppression automatique des versions des services non utilisés

== Gestion d'un service via le ServiceFactory

[plantuml, format="svg", role="right"]
....
legend
Legend
endlegend

node Client

node Server {
    component "Reverse Proxy" as ReverseProxy
    component ServiceFactory
    component Service1
    component ServiceX

    ReverseProxy -left- ServiceFactory
    ServiceFactory -down- Service1
    ServiceFactory -down- ServiceX
    ReverseProxy -down- Service1
    ReverseProxy -down- ServiceX
}

Client -right- ReverseProxy
....

C'est par l'intermédiaire d'un reverse proxy que le client pourra communiquer avec :

* Un ServiceFactory
* Un service

== Description du ServiceFactory

Le ServiceFactory à pour rôle de gérer les services qui auront été créés suite à une demande d'execution d'un client.

Un client peut faire une demande, au ServiceFactory, de :

[%header,cols=2*]
|===
|Action  |Description

|Connection
|La connection à pour rôle de créer un nouveau service qui sera associé au client.

|Déconnection
|La déconnection à pour rôle de stopper un service associé à un client.
|===

== Routes ServiceFactory

Les communication avec le ServiceFactory doivent se faire sur l'url suivante : `ServiceFactory.domain.tld`.

[%header,cols=4*]
|===
|Verbe HTTP |Route |Données  |Réponse

|POST
|/client/login
a|
[source,json]
{
    "username": String,
    "password": String
    "broker": String
    "accountType": String
}
a|
[source]
Status Code : 200

[source,json]
{
    "urlws": String
}

|POST
|/client/logout
a|
[source,json]
{
    "urlws": String
}
a|
[source]
Status Code : 202

[source,json]
{
    "status": Boolean
}
|===

Les informations (informations de connection à un compte de trading) transmises par l'intermediaire des routes sont transmises au service pour sa création.