= Description du service factory
:toc: left

Le service factory est un module qui permet la création d'un service en fonction d'une demande client.

== Gestion d'un service via le service factory

[plantuml, format="svg", role="right"]
....
legend
Legend
endlegend

node Client

node Server {
    component "Reverse Proxy" as ReverseProxy
    component "Service Factory" as ServiceFactory
    component Service1
    component ServiceX

    ReverseProxy -left- ServiceFactory
    ServiceFactory -down- Service1
    ServiceFactory -down- ServiceX
    ReverseProxy -down- Service1
    ReverseProxy -down- ServiceX
}

Client -right- ReverseProxy
....

C'est par l'intermédiaire d'un reverse proxy que le client pourra communiquer avec :

* Un service factory
* Un service

== Description du service factory

Le service factory à pour rôle de gérer les services qui auront été créés suite à une demande d'execution d'un client.

Un client peut faire une demande, au service factory, de :

[%header,cols=3*]
|===
|Référence |Action  |Description

|1
|Création compte
|Créer un compte utilisateur

|2
|Création service
|Créer un service

|3
|Destruction service
|Détruire un service


|4
|Ajout
|Ajouter un compte de trading

|5
|Liste
|Lister les comptes de trading

|6
|Suppression
|Supprimer les comptes de trading

|7
|Modification
|Modifier les comptes de trading


|8
|Suppression compte perso
|Supprimer un compte personnel

|9
|Mot de passe oublié
|Réinitialisation du mot de passe

|10
|Liste Brokers
|Lister les Brokers

|11
|Connection
|Se connecter

|===

== Routes service factory

Les communication avec le service factory doivent se faire sur l'url suivante : `service_factory.domain.tld`.

[%header,cols=5*]
|===
|Référence |Verbe HTTP |Route |Données  |Réponse

|1
|POST
|/users
a|
[source,json]
{
    "email": String,
    "password": String
}
a|
[source]
Status Code : 201

[source,json]
{
    "id": Integer
}

|2
|POST
|/services
a|
[source,json]
{
    "token": String,
    "username": String,
    "password": String,
    "broker": String,
    "accountType": String
}
a|
[source]
Status Code : 200

[source,json]
{
    "urlws": String
}

|3
|DELETE
|/services/{id}
a|
[source,json]
{
    "token": String
}
a|
[source]
Status Code : 204
|4
|POST
|/trading-accounts
a|
[source,json]
{
    "token": String
    "type compte": String
    "brokername": String
    "username": String
    "password": String
}
a|
[source]
Status Code : 201

[source,json]
{
    "id": Integer
}

|5
|GET
|/trading-accounts
a|
[source,json]
{
    "token": String
}
a|
[source]
Status Code : 202

[source,json]
[{
     "type compte": String
     "brokername": String
     "username": String
     "password": String
 }]
|6
|DELETE
|/trading-accounts/{id}
a|
[source,json]
{
    "token": String
}
a|
[source]
Status Code : 204
|7
|PUT
|/trading-accounts/{id}
a|
[source,json]
{
    "token": String
    "type compte": String
    "brokername": String
    "username": String
    "password": String
}
a|
[source]
Status Code : 201
|8
|DELETE
|/users/{id}
a|
[source,json]
{
    "token": String
}
a|
[source]
Status Code : 204
|9
|POST
|/users/forgot
a|
[source,json]
{
    "email": String
}
a|
[source]
Status Code : 201

|10
|GET
|/brokers
a|
[source,json]
{
    "token": String
}
a|
[source]
Status Code : 200

[source,json]
[{
     "brokername": String,
     "broker_id": String
 }]

|11
|POST
|/users/auth
a|
[source,json]
{
    "email": String
    "password": String
}
a|
[source]
Status Code : 201

[source,json]
{
    "token": String
}
|===

Les informations (informations de connection à un compte de trading) transmises par l'intermediaire des routes sont transmises au service pour sa création.