= Spécifications techniques détaillées
:toc: left

L'architecture globale de communication entre les différents éléments est le suivant :

[%header,cols=2*]
|===
| Rôle | Description

|User
|Interagie directement avec la partie Client de l'application

|Client
|Communique directement avec la partie Server

|Server
|Reçoit les communications en provenance des Clients et interagie avec les Data

|Data
|Permet soit le stockage des données en provenance du server, soit correspond à une API externe (ex: broker)
|===

[plantuml, format="svg"]
....
actor User

node Client
node Server
database Data

User -right- Client
Client -right- Server
Server -right- Data
....

== Architecture structurelle (modules)

Certaines informations entre la partie Client et Server vont être communes. Afin de faciliter la communication entre les différents module, un module API sera créé et importé dans chacun des autres module.

[plantuml, format="svg"]
....
node API
node Client
node Server

API -- Client
API -- Server
....

Il sera donc nécessaire de créer des sous modules Git afin d'importé facilement les projets. C'est-à-dire que le module API est un sous module Git du repository qui hebergera le module Client ou encore Server.

== Structure d'un projet

Un projet doit être strucuté de la façon suivante :

[plantuml, format="svg"]
....
salt
{
{T
 + Project name
 ++ api
 ++ app
 ++ gradle files
}
}
....

Chaque dossier positionné à la racine est un module. Est automatiquement importé, le module API.

== Détails des spécifications

[%header,cols=2*]
|===
| Document | Description

|link:stdconnector.html[Connecteur]
|Permet de détailler le fonctionnement d'un connecteur.

|link:stdservice.html[Service]
|Permet de décrire le fonctionnement du service.

|link:stdalgorithm.html[Algortihme]
|Permet d'expliquer les éléments techniques d'un algorithme de trading.

|link:stddeployment.html[Déploiement]
|Permet de présenter le procéssus de déploiement de l'application.

|link:trading-plateforme.html[Plateforme de trading]
|Permet de décrire les éléments techniques de la plateforme de trading.
|===
