= Spécifications techniques d'un service
:toc: left

== Service

Le service est la partie de l'architecture qui permet :

* La connexion d'un compte de trading
* La récupération des cotations
* La transmission des transactions

== Architecture d'un Service

[plantuml, format="svg", role="right"]
....
node Service
database Database
node Connecteur
node Indicateur

Service -down- Database
Service -down- Connecteur
Service -down- Indicateur
....

Un Service est un module autonome permettant de :

* Communiquer avec une base de données
* Charger un Connecteur
* Charger des Indicateurs techniques

=== Description d'un service

Le Service réception les demandes du Client pour :

* Transmettre les données à une base de données
* Transmettre des données à une l'API

Lors de sa création, le service reçoit toutes les informations nécessaires pour se connecter à connecteur.

=== La Database

La base de données permet la persistances des données en provenance :

* des demandes Client -> Service.
* des données Connecteur -> Service.

=== Le Connecteur

Doit être permettre la communication entre le Service et un broker. Elle doit permettre de :

* Récupérer les cotations des instruments financiers.
* Récupérer les informations d'un compte de trading.
* Transmettre des transactions.

Le Connecteur utiliser l'Api qui est fourni par le Broker.

== Communication entre le Service et les Connecteurs

Un connecteur est un module permettant la communication entre un Service et un broker.

[plantuml, format="svg"]
....
node Service
node Broker1
node Broker2
node BrokerX

Service -down- Broker1
Service -down- Broker2
Service -down- BrokerX
....

L'initialisation d'un service charge automatiquement l'ensemble des manifests des connecteurs. Néanmoins seulement un connecteur sera chargé.