= Spécifications techniques d'un service
:toc: left

== Chargement des connecteurs

Un serveur doit pouvoir charger un connecteur de façon dynamique.

== Attribution d'un service à un client

[plantuml, format="svg", role="right"]
....
node Client

node Server {
    component "Reverse Proxy" as ReverseProxy
    component Dispatcher
    component Service1
    component ServiceX

    ReverseProxy -left- Dispatcher
    Dispatcher -down- Service1
    Dispatcher -down- ServiceX
    ReverseProxy -down- Service1
    ReverseProxy -down- ServiceX
}

Client -right- ReverseProxy
....

C'est par l'intermédiaire d'un reverse proxy que le client pourra communiquer avec :

* Un dispatcher
* Un service

=== Dispatcher

Le dispatcher à pour rôle de gérer les services qui auront été créé suite à une demande de connexion d'un client.

Un client peut faire une demande de :

[%header,cols=2*]
|===
|Action  |Description

|Connection
|La connection à pour rôle de créer un nouveau service qui sera associé au client.

|Déconnection
|La déconnection à pour rôle de stopper un service associé à un client.
|===

==== Routes Dispatcher

Les communication avec le dispatcher doivent se faire sur l'url suivante : `dispatcher.domain.tld`.

[%header,cols=4*]
|===
|Verbe HTTP |Route |Données  |Réponse

|POST
|/client/login
a|
[source,json]
{
    "username": String,
    "password": String
    "broker": String
    "accountType": String
}
a|
[source]
Status Code : 200

[source,json]
{
    "urlws": String
}

|POST
|/client/logout
a|
[source,json]
{
    "urlws": String
}
a|
[source]
Status Code : 202

[source,json]
{
    "status": Boolean
}
|===

=== Service

Le service est la partie de l'architecture qui permet :

* La connexion d'un compte de trading
* La récupération des cotations
* La transmission des transactions

== Architecture d'un Service

[plantuml, format="svg", role="right"]
....
node Service
database Database
node Connecteur
node Indicateur

Service -down- Database
Service -down- Connecteur
Service -down- Indicateur
....

Un Service est un module autonome permettant de :

* Communiquer avec une base de données
* Charger un Connecteur
* Charger des Indicateurs techniques

=== Le Service

Le Service réception les demandes du Client pour :

* Transmettre les données à une base de données
* Transmettre des données à une l'API

=== La Database

La base de données permet la persistances des données en provenance :

* des demandes Client -> Service.
* des données Connecteur -> Service.

=== Le Connecteur

Doit être permettre la communication entre le Service et un broker. Elle doit permettre de :

* Récupérer les cotations des instruments financiers.
* Récupérer les informations d'un compte de trading.
* Transmettre des transactions.

Le Connecteur utiliser l'Api qui est fourni par le Broker.

== Communication entre le Service et les Connecteurs

Un connecteur est un module permettant la communication entre un Service et un broker. Le connecteur utilise l'Api que propose un broker.

[plantuml, format="svg"]
....
node Service
node Broker1
node Broker2
node BrokerX

Service -down- Broker1
Service -down- Broker2
Service -down- BrokerX
....